version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gold_prices
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gold_prices_network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

  gold_prices_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
